[package]
authors = ["Dilshod Tadjibaev (@antimora)"]
license = "MIT OR Apache-2.0"
name = "mnist-inference-web"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["flex"]

flex = ["burn/flex"]
wgpu = ["burn/wgpu"]

[dependencies]
burn = { version = "0.21.0", default-features = false, features = ["ndarray", "store"] }
serde = { version = "1.0.228", default-features = false }
console_error_panic_hook = { version = "*" }
# Wasm dependencies
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
# Featurize
featurize-core = { path = "../core" }
