[package]
name = "featurize-core"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = { version = "0.2", default-features = false, features = ["libm"] }

[dev-dependencies]
trybuild = "1.0"
proptest = "1.0"
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "profile"
harness = false

[[test]]
name = "prop_tests"
